### Contributors: Brian Waweru
### Date        : 08th May, 2025

In [ ]:
# Python Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

## Feature Engineering and Preprocessing

In [80]:
# dataset location
file = "churn_in_telecoms_dataset.csv"
# creating a dataframe
df = pd.read_csv(file)
# shape of the dataset
print(df.shape)
# drop the 'phone number' column
df = df.drop(columns='phone number')
# columns
print(df.columns)

(3333, 21)
Index(['state', 'account length', 'area code', 'international plan',
       'voice mail plan', 'number vmail messages', 'total day minutes',
       'total day calls', 'total day charge', 'total eve minutes',
       'total eve calls', 'total eve charge', 'total night minutes',
       'total night calls', 'total night charge', 'total intl minutes',
       'total intl calls', 'total intl charge', 'customer service calls',
       'churn'],
      dtype='object')


In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   state                   3333 non-null   object 
 1   account length          3333 non-null   int64  
 2   area code               3333 non-null   int64  
 3   international plan      3333 non-null   object 
 4   voice mail plan         3333 non-null   object 
 5   number vmail messages   3333 non-null   int64  
 6   total day minutes       3333 non-null   float64
 7   total day calls         3333 non-null   int64  
 8   total day charge        3333 non-null   float64
 9   total eve minutes       3333 non-null   float64
 10  total eve calls         3333 non-null   int64  
 11  total eve charge        3333 non-null   float64
 12  total night minutes     3333 non-null   float64
 13  total night calls       3333 non-null   int64  
 14  total night charge      3333 non-null   

In [57]:
# finding out entries of the 'churn' column
print(df.churn.unique())
# >>> array([False,  True])
df['churn'] = df['churn'].astype(int)
# Convert boolean values in the 'churn' column to integers: False → 0, True → 1
df.churn.unique()

[False  True]


array([0, 1])

In [ ]:
# Categorical Columns
missing_columns = [col for col in df.columns if col not in df.describe().columns]
print("Columns missing from df.describe():", missing_columns)
# printing them out
df[['state', 'international plan', 'voice mail plan']].head(3)

Columns missing from df.describe(): ['state', 'international plan', 'voice mail plan']


state international plan voice mail plan
0    KS                 no             yes
1    OH                 no             yes
2    NJ                 no              no
3    OH                yes              no
4    OK                yes              no

In [ ]:
print(df.shape)
df['area code'].unique() # 3 

(3333, 20)


array([415, 408, 510], dtype=int64)

# Overview